// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCcuTsrEBmZNMwFLciZxbp5sbiJ1RWSvM', // TODO: Update from Firebase Console
    appId: '1:148043153053:web:your-web-app-id', // TODO: Update from Firebase Console
    messagingSenderId: '148043153053',
    projectId: 'fortumars-hrms-63078',
    authDomain: 'fortumars-hrms-63078.firebaseapp.com',
    storageBucket: 'fortumars-hrms-63078.firebasestorage.app',
  );

  // Web Firebase configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95UyPhJf4FpLbZL0kyisx5BnKj5zBPb8', // From google-services.json
    appId: '1:933599410604:android:05eeb09398420971936209', // From google-services.json
    messagingSenderId: '933599410604',
    projectId: 'myproject-f9e45',
    storageBucket: 'myproject-f9e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7kDPb4S6RSS2OtXwV6GwMB8Y2nn1DAg', // From GoogleService-Info.plist
    appId: '1:148043153053:ios:f6fa9b2e7d10084c835e74', // From GoogleService-Info.plist
    messagingSenderId: '148043153053',
    projectId: 'fortumars-hrms-63078',
    storageBucket: 'fortumars-hrms-63078.firebasestorage.app',
    iosBundleId: 'com.fortumars-hrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7kDPb4S6RSS2OtXwV6GwMB8Y2nn1DAg', // From iOS config
    appId: '1:148043153053:ios:f6fa9b2e7d10084c835e74', // From iOS config
    messagingSenderId: '148043153053',
    projectId: 'fortumars-hrms-63078',
    storageBucket: 'fortumars-hrms-63078.firebasestorage.app',
    iosBundleId: 'com.fortumars-hrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCcuTsrEBmZNMwFLciZxbp5sbiJ1RWSvM', // TODO: Update from Firebase Console
    appId: '1:148043153053:web:your-web-app-id', // TODO: Update from Firebase Console
    messagingSenderId: '148043153053',
    projectId: 'fortumars-hrms-63078',
    authDomain: 'fortumars-hrms-63078.firebaseapp.com',
    storageBucket: 'fortumars-hrms-63078.firebasestorage.app',
  );

}